export const tasks = [
  {
    id: 'TASK-9674',
    title: "I'll transmit the optical SMTP pixel, that should circuit the AI bus!",
    status: 'done',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-4540',
    title: "Backing up the array won't do anything, we need to hack the auxiliary AI hard drive!",
    status: 'in progress',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-1553',
    title: "Hacking the capacitor won't do anything, we need to generate the mobile AI transmitter!",
    status: 'backlog',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-5833',
    title: "I'll transmit the open-source DNS application, that should driver the JBOD card!",
    status: 'todo',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-7223',
    title: "Indexing the monitor won't do anything, we need to quantify the open-source ADP sensor!",
    status: 'todo',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-6048',
    title: 'We need to generate the haptic CSS capacitor!',
    status: 'in progress',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-3173',
    title: "You can't input the capacitor without generating the primary CSS system!",
    status: 'todo',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-1292',
    title: "I'll copy the bluetooth SMS bandwidth, that should microchip the AI feed!",
    status: 'in progress',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-7009',
    title: 'Use the multi-byte JSON hard drive, then you can bypass the back-end driver!',
    status: 'todo',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-3812',
    title: 'Try to back up the EXE feed, maybe it will index the redundant protocol!',
    status: 'todo',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-9968',
    title: "Calculating the matrix won't do anything, we need to navigate the optical SDD alarm!",
    status: 'done',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-9748',
    title: 'If we transmit the hard drive, we can get to the DNS port through the digital VGA panel!',
    status: 'backlog',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-1089',
    title: 'Try to copy the SSD system, maybe it will index the haptic monitor!',
    status: 'canceled',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-3379',
    title: 'Try to hack the SSD firewall, maybe it will program the open-source hard drive!',
    status: 'in progress',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-1687',
    title: "I'll index the wireless API driver, that should application the IB card!",
    status: 'todo',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-6251',
    title: "You can't reboot the capacitor without quantifying the primary SDD alarm!",
    status: 'in progress',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-1080',
    title: "I'll hack the solid state SMTP interface, that should microchip the RAM firewall!",
    status: 'in progress',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-3452',
    title: "You can't generate the protocol without transmitting the wireless UTF8 sensor!",
    status: 'todo',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-7208',
    title: 'We need to generate the digital USB hard drive!',
    status: 'in progress',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-9468',
    title: 'We need to input the cross-platform DRAM array!',
    status: 'done',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-5482',
    title: "I'll override the haptic JBOD card, that should system the SDD bandwidth!",
    status: 'backlog',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-5641',
    title: "I'll synthesize the primary RSS alarm, that should driver the AGP sensor!",
    status: 'backlog',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-1569',
    title: 'The DNS bandwidth is down, input the virtual bus so we can parse the SAS array!',
    status: 'in progress',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-3895',
    title: 'We need to override the solid state FTP program!',
    status: 'backlog',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-4392',
    title: 'Try to calculate the SAS capacitor, maybe it will reboot the wireless firewall!',
    status: 'backlog',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-3048',
    title: "You can't quantify the capacitor without backing up the primary COM port!",
    status: 'in progress',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-9535',
    title: "You can't reboot the bandwidth without compressing the auxiliary CSS program!",
    status: 'done',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-6585',
    title: "I'll calculate the cross-platform SDD alarm, that should protocol the COM driver!",
    status: 'todo',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-3178',
    title: 'Try to transmit the COM interface, maybe it will synthesize the online sensor!',
    status: 'canceled',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-5906',
    title: 'Use the primary COM microchip, then you can synthesize the auxiliary protocol!',
    status: 'todo',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-9533',
    title: 'If we synthesize the pixel, we can get to the OCR transmitter through the open-source IP card!',
    status: 'done',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-8528',
    title: 'Try to input the RSS array, maybe it will connect the solid state sensor!',
    status: 'backlog',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-7875',
    title: 'If we synthesize the interface, we can get to the USB sensor through the cross-platform JSON system!',
    status: 'in progress',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-4126',
    title: 'Use the auxiliary TLS array, then you can quantify the cross-platform alarm!',
    status: 'done',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-9768',
    title: 'Try to hack the SCSI firewall, maybe it will bypass the redundant interface!',
    status: 'canceled',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-9854',
    title: 'Use the open-source SAS alarm, then you can back up the auxiliary capacitor!',
    status: 'canceled',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-2565',
    title: 'Use the haptic USB monitor, then you can synthesize the 1080p sensor!',
    status: 'done',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-6660',
    title: 'Try to hack the VGA program, maybe it will synthesize the bluetooth driver!',
    status: 'todo',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-7728',
    title: 'Use the mobile FTP program, then you can connect the bluetooth hard drive!',
    status: 'todo',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-7170',
    title: 'Use the redundant SCSI interface, then you can navigate the virtual monitor!',
    status: 'canceled',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-3546',
    title: "You can't synthesize the port without hacking the auxiliary RSS hard drive!",
    status: 'todo',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-3598',
    title: "I'll navigate the 1080p CLI alarm, that should firewall the API alarm!",
    status: 'canceled',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-5679',
    title: 'If we synthesize the sensor, we can get to the AI port through the cross-platform XML hard drive!',
    status: 'canceled',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-8840',
    title: "I'll hack the mobile PCI driver, that should monitor the IP system!",
    status: 'in progress',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-5363',
    title: "You can't calculate the program without bypassing the neural EXE system!",
    status: 'canceled',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-3651',
    title: 'Try to quantify the GB capacitor, maybe it will connect the primary alarm!',
    status: 'todo',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-6395',
    title: "You can't program the capacitor without synthesizing the optical JSON matrix!",
    status: 'in progress',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-6617',
    title: "I'll navigate the online JBOD circuit, that should capacitor the IP alarm!",
    status: 'done',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-4250',
    title: "Copying the microchip won't do anything, we need to program the bluetooth RSS system!",
    status: 'done',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-6553',
    title: 'Try to copy the USB monitor, maybe it will compress the primary program!',
    status: 'todo',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-7418',
    title: 'We need to connect the cross-platform HDD bus!',
    status: 'backlog',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-7901',
    title: 'The SAS interface is down, input the open-source alarm so we can transmit the SMTP microchip!',
    status: 'canceled',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-6783',
    title: "I'll hack the neural IP firewall, that should alarm the SSL circuit!",
    status: 'backlog',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-8067',
    title: 'The PCI firewall is down, hack the 1080p driver so we can quantify the TCP microchip!',
    status: 'todo',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-1513',
    title: "You can't hack the microchip without backing up the optical AI firewall!",
    status: 'backlog',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-5775',
    title: 'The FTP microchip is down, parse the online feed so we can generate the CLI bus!',
    status: 'done',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-7821',
    title: 'The UDP program is down, compress the neural port so we can quantify the RSS microchip!',
    status: 'in progress',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-8125',
    title: "You can't override the capacitor without programming the wireless SSD port!",
    status: 'canceled',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-2293',
    title: "Navigating the bandwidth won't do anything, we need to connect the neural OCR pixel!",
    status: 'in progress',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-5814',
    title: 'If we transmit the array, we can get to the HEX program through the solid state HTTP panel!',
    status: 'todo',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-8192',
    title: 'The UTF8 monitor is down, generate the solid state bandwidth so we can override the USB alarm!',
    status: 'done',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-7378',
    title: "Hacking the interface won't do anything, we need to synthesize the multi-byte TLS alarm!",
    status: 'in progress',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-9200',
    title: "Hacking the capacitor won't do anything, we need to hack the optical RSS system!",
    status: 'todo',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-8136',
    title: 'If we synthesize the circuit, we can get to the SCSI circuit through the wireless SMS firewall!',
    status: 'canceled',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-3154',
    title: "You can't copy the alarm without compressing the auxiliary CLI port!",
    status: 'backlog',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-8337',
    title: 'If we transmit the port, we can get to the JSON monitor through the open-source XSS interface!',
    status: 'backlog',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-2730',
    title: 'Use the auxiliary UDP program, then you can generate the primary firewall!',
    status: 'todo',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-9826',
    title: "I'll index the online GB microchip, that should port the HDD firewall!",
    status: 'canceled',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-7461',
    title: "You can't index the bus without hacking the solid state API feed!",
    status: 'done',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-3514',
    title: "You can't back up the pixel without quantifying the virtual THX panel!",
    status: 'todo',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-8589',
    title: 'The SDD card is down, reboot the optical firewall so we can index the HTTP feed!',
    status: 'canceled',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-4014',
    title: 'Try to navigate the SQL sensor, maybe it will back up the optical monitor!',
    status: 'in progress',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-7689',
    title: 'If we copy the feed, we can get to the COM sensor through the haptic GB card!',
    status: 'in progress',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-1868',
    title: "You can't index the circuit without calculating the online IB interface!",
    status: 'in progress',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-1099',
    title: "Navigating the sensor won't do anything, we need to input the redundant SMTP system!",
    status: 'todo',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-3362',
    title: "Compressing the sensor won't do anything, we need to copy the solid state THX interface!",
    status: 'backlog',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-1756',
    title: "Calculating the interface won't do anything, we need to generate the solid state EXE matrix!",
    status: 'done',
    label: 'documentation',
    priority: 'low',
  },
  {
    id: 'TASK-8594',
    title: 'Use the optical IB program, then you can quantify the cross-platform port!',
    status: 'backlog',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-5728',
    title: 'Use the wireless SSD application, then you can reboot the multi-byte system!',
    status: 'done',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-1019',
    title: 'The HTTP capacitor is down, navigate the online hard drive so we can navigate the IP application!',
    status: 'backlog',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-7239',
    title: 'Try to input the DNS bus, maybe it will transmit the digital matrix!',
    status: 'todo',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-3377',
    title: "You can't quantify the array without quantifying the cross-platform SMTP feed!",
    status: 'in progress',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-7248',
    title: 'Try to override the PCI panel, maybe it will synthesize the optical circuit!',
    status: 'todo',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-8180',
    title: 'If we compress the capacitor, we can get to the JBOD panel through the online OCR transmitter!',
    status: 'todo',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-8354',
    title: "You can't quantify the bandwidth without connecting the wireless XML bus!",
    status: 'done',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-3024',
    title: 'The TLS driver is down, copy the solid state feed so we can transmit the HDD transmitter!',
    status: 'backlog',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-3276',
    title: 'The FTP bandwidth is down, calculate the mobile alarm so we can hack the JSON feed!',
    status: 'todo',
    label: 'documentation',
    priority: 'high',
  },
  {
    id: 'TASK-5787',
    title: "Copying the alarm won't do anything, we need to parse the primary FTP array!",
    status: 'backlog',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-6623',
    title: 'If we calculate the feed, we can get to the CSS application through the 1080p HDD pixel!',
    status: 'done',
    label: 'feature',
    priority: 'medium',
  },
  {
    id: 'TASK-8935',
    title: "Generating the firewall won't do anything, we need to index the cross-platform ASCII transmitter!",
    status: 'todo',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-5675',
    title: "I'll hack the cross-platform AGP bus, that should panel the XML bus!",
    status: 'backlog',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-2533',
    title: 'The USB firewall is down, back up the haptic feed so we can generate the SCSI port!',
    status: 'done',
    label: 'feature',
    priority: 'low',
  },
  {
    id: 'TASK-3353',
    title: 'The AI bandwidth is down, back up the optical matrix so we can compress the EXE hard drive!',
    status: 'backlog',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-2947',
    title: 'If we parse the interface, we can get to the JSON feed through the haptic ASCII matrix!',
    status: 'todo',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-7104',
    title: "You can't input the capacitor without synthesizing the optical SDD capacitor!",
    status: 'backlog',
    label: 'documentation',
    priority: 'medium',
  },
  {
    id: 'TASK-3585',
    title: "I'll index the wireless GB panel, that should alarm the UTF8 transmitter!",
    status: 'todo',
    label: 'bug',
    priority: 'high',
  },
  {
    id: 'TASK-6740',
    title: 'Try to navigate the THX alarm, maybe it will parse the multi-byte alarm!',
    status: 'in progress',
    label: 'feature',
    priority: 'high',
  },
  {
    id: 'TASK-4102',
    title: "Compressing the sensor won't do anything, we need to navigate the virtual DRAM protocol!",
    status: 'in progress',
    label: 'bug',
    priority: 'medium',
  },
  {
    id: 'TASK-6116',
    title: 'If we compress the transmitter, we can get to the TLS alarm through the wireless UTF8 system!',
    status: 'done',
    label: 'bug',
    priority: 'low',
  },
  {
    id: 'TASK-4359',
    title: 'If we hack the sensor, we can get to the DRAM interface through the haptic TLS bandwidth!',
    status: 'todo',
    label: 'bug',
    priority: 'medium',
  },
]
